// الترجمات العربية — جميع نصوص الواجهة
const Map<String, String> ar = {
  // General
  'app_name': 'تطبيق التوصيل',
  'loading': 'جاري التحميل...',
  'retry': 'إعادة المحاولة',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'save': 'حفظ',
  'delete': 'حذف',
  'edit': 'تعديل',
  'add': 'إضافة',
  'search': 'بحث',
  'filter': 'تصفية',
  'no_data': 'لا توجد بيانات',
  'error_occurred': 'حدث خطأ',
  'success': 'تمت العملية بنجاح',
  'yes': 'نعم',
  'no': 'لا',
  'ok': 'حسناً',
  'close': 'إغلاق',
  'back': 'رجوع',
  'next': 'التالي',
  'previous': 'السابق',
  'done': 'تم',
  'skip': 'تخطي',
  'see_all': 'عرض الكل',
  'total': 'الإجمالي',
  'details': 'التفاصيل',

  // Auth
  'login': 'تسجيل الدخول',
  'register': 'إنشاء حساب',
  'logout': 'تسجيل الخروج',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'confirm_password': 'تأكيد كلمة المرور',
  'phone': 'رقم الهاتف',
  'full_name': 'الاسم الكامل',
  'address': 'العنوان',
  'forgot_password': 'نسيت كلمة المرور؟',
  'change_password': 'تغيير كلمة المرور',
  'old_password': 'كلمة المرور الحالية',
  'new_password': 'كلمة المرور الجديدة',
  'select_role': 'اختر نوع الحساب',
  'customer': 'عميل',
  'driver': 'سائق',
  'representative': 'مندوب',
  'admin': 'مدير',
  'login_as_customer': 'دخول كعميل',
  'login_as_driver': 'دخول كسائق',
  'login_as_representative': 'دخول كمندوب',
  'login_as_admin': 'دخول كمدير',
  'register_as_customer': 'تسجيل حساب عميل',
  'dont_have_account': 'ليس لديك حساب؟',
  'already_have_account': 'لديك حساب بالفعل؟',
  'registration_pending': 'حسابك قيد المراجعة',
  'registration_pending_message': 'تم إرسال طلب التسجيل بنجاح. سيتم مراجعته والموافقة عليه قريباً.',

  // Validation
  'required_field': 'هذا الحقل مطلوب',
  'invalid_email': 'البريد الإلكتروني غير صحيح',
  'invalid_phone': 'رقم الهاتف غير صحيح',
  'password_too_short': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
  'passwords_not_match': 'كلمات المرور غير متطابقة',

  // Onboarding
  'onboarding_title_1': 'مرحباً بك',
  'onboarding_desc_1': 'أسهل طريقة لطلب منتجاتك المفضلة وتوصيلها لباب بيتك',
  'onboarding_title_2': 'تتبع طلباتك',
  'onboarding_desc_2': 'تابع حالة طلبك لحظة بلحظة حتى يصل إليك',
  'onboarding_title_3': 'دفع آمن',
  'onboarding_desc_3': 'طرق دفع متعددة وآمنة تناسب جميع احتياجاتك',
  'get_started': 'ابدأ الآن',

  // Customer
  'home': 'الرئيسية',
  'products': 'المنتجات',
  'categories': 'الأقسام',
  'cart': 'السلة',
  'my_orders': 'طلباتي',
  'order_details': 'تفاصيل الطلب',
  'my_debts': 'مديونياتي',
  'checkout': 'إتمام الطلب',
  'add_to_cart': 'أضف إلى السلة',
  'remove_from_cart': 'إزالة من السلة',
  'cart_empty': 'السلة فارغة',
  'quantity': 'الكمية',
  'price': 'السعر',
  'subtotal': 'المجموع الفرعي',
  'delivery_fee': 'رسوم التوصيل',
  'notes': 'ملاحظات',
  'place_order': 'تأكيد الطلب',
  'order_placed': 'تم تأكيد الطلب بنجاح',
  'product_details': 'تفاصيل المنتج',
  'available': 'متوفر',
  'out_of_stock': 'غير متوفر',

  // Order Status
  'status_pending': 'قيد الانتظار',
  'status_approved': 'تمت الموافقة',
  'status_in_progress': 'قيد التجهيز',
  'status_shipped': 'تم الشحن',
  'status_delivered': 'تم التوصيل',
  'status_cancelled': 'ملغي',
  'status_rejected': 'مرفوض',

  // Driver
  'assigned_orders': 'الطلبات المسندة',
  'completed_deliveries': 'التوصيلات المكتملة',
  'order_tracking': 'تتبع الطلب',
  'mark_delivered': 'تأكيد التوصيل',
  'start_delivery': 'بدء التوصيل',
  'delivery_address': 'عنوان التوصيل',
  'customer_phone': 'هاتف العميل',

  // Representative
  'my_customers': 'عملائي',
  'register_customer': 'تسجيل عميل جديد',
  'customer_invoices': 'فواتير العميل',
  'collect_payment': 'تحصيل دفعة',
  'payment_amount': 'مبلغ الدفعة',
  'payment_collected': 'تم تحصيل الدفعة بنجاح',

  // Admin
  'dashboard': 'لوحة التحكم',
  'manage_customers': 'إدارة العملاء',
  'pending_approvals': 'طلبات الموافقة',
  'manage_representatives': 'إدارة المندوبين',
  'manage_drivers': 'إدارة السائقين',
  'manage_products': 'إدارة المنتجات',
  'manage_categories': 'إدارة الأقسام',
  'manage_warehouses': 'إدارة المستودعات',
  'manage_inventory': 'إدارة المخزون',
  'manage_invoices': 'إدارة الفواتير',
  'customer_statement': 'كشف حساب العميل',
  'analytics': 'التحليلات',
  'debts_settlement': 'تسوية المديونيات',
  'activity_logs': 'سجل النشاطات',
  'approve': 'موافقة',
  'reject': 'رفض',
  'total_customers': 'إجمالي العملاء',
  'total_orders': 'إجمالي الطلبات',
  'total_revenue': 'إجمالي الإيرادات',
  'total_products': 'إجمالي المنتجات',
  'pending_orders': 'طلبات معلقة',
  'total_debts': 'إجمالي المديونيات',

  // Notifications
  'notifications': 'الإشعارات',
  'no_notifications': 'لا توجد إشعارات',
  'mark_all_read': 'تعيين الكل كمقروء',

  // Settings
  'settings': 'الإعدادات',
  'profile': 'الملف الشخصي',
  'edit_profile': 'تعديل الملف الشخصي',
  'theme_settings': 'إعدادات المظهر',
  'dark_mode': 'الوضع الداكن',
  'light_mode': 'الوضع الفاتح',
  'about_app': 'عن التطبيق',
  'privacy_policy': 'سياسة الخصوصية',
  'technical_support': 'الدعم الفني',
  'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
  'version': 'الإصدار',

  // Errors
  'connection_error': 'خطأ في الاتصال بالإنترنت',
  'server_error': 'خطأ في الخادم',
  'unauthorized': 'غير مصرح لك بالدخول',
  'session_expired': 'انتهت الجلسة، يرجى تسجيل الدخول مرة أخرى',
  'unknown_error': 'حدث خطأ غير متوقع',
  'not_found': 'غير موجود',
  'bad_request': 'طلب غير صحيح',
};
